//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Database_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenti
    {
        public short Matricola { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string email { get; set; }
        public string classe { get; set; }
    }
}
